feat: use esm
oclif/plugin-warn-if-update-available pull request #400
Opened 2023-07-21 03:06 UTC by mshanemc

experiment with ESM.  Seems to work ok when I copy the js and pjson into `sf` locally

2023-07-24 20:23 UTC, mdonnalley requested changes
You need to also follow the instructions here: https://oclif.io/docs/esm

2023-07-25 13:46 UTC, mshanemc commented
> You need to also follow the instructions here: https://oclif.io/docs/esm in order for local development to work

Cool, I didn't know we had that.  

Notes:
1. `// eslint-disable-next-line node/no-unpublished-import` was unnecessary
2. There was not a bin in the package.json.  I'm guessing plugins wouldn't have that (ours don't), but CLI's would?  The docs start off as "in your plugin or CLI" but I think switched to "for CLIs..." there.

2023-07-25 14:17 UTC, mdonnalley approved these changes

2023-07-26 15:12 UTC, mdonnalley commented on package.json
> +    "node": ">=16.0.0"
@mshanemc should we keep this at 14 until we update oclif/core to 16?

2023-10-17 18:25 UTC, closed without merging